import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import UserPanelTop from './UserPanelTop'
import { ThemeProvider } from './[components]/theme-provider'
import {notFound} from 'next/navigation';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const locales = ['en', 'de'];
 

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" >
      <body className={inter.className}>
        <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <UserPanelTop/>
              {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
